const FETCH_USER_EMPLOYEES = 'FETCH_USER_EMPLOYEES';
const SEARCH_USER_EMPLOYEES = 'SEARCH_USER_EMPLOYEES';
const EMPLOYEES_CLEAR = 'EMPLOYEES_CLEAR';
const EMPLOYEES_SORT_BY = 'EMPLOYEES_SORT_BY';
const EMPLOYEES_SORT_ORDER = 'EMPLOYEES_SORT_ORDER';
const EMPLOYEES_SELECT_ELEMENT = 'EMPLOYEES_SELECT_ELEMENT';
const EMPLOYEES_UNSELECT_ELEMENT = 'EMPLOYEES_UNSELECT_ELEMENT';
const EMPLOYEES_RESET_SELECTED = 'EMPLOYEES_RESET_SELECTED';
const EMPLOYEES_TOGGLE_SELECT_ALL = 'EMPLOYEES_TOGGLE_SELECT_ALL';
const EMPLOYEES_PAGINATION_VALUE = 'EMPLOYEES_PAGINATION_VALUE';
const EMPLOYEES_CURRENT_PAGE = 'EMPLOYEES_CURRENT_PAGE';

export default {
   FETCH_USER_EMPLOYEES,
   SEARCH_USER_EMPLOYEES,
   EMPLOYEES_CLEAR,
   EMPLOYEES_SORT_BY,
   EMPLOYEES_SORT_ORDER,
   EMPLOYEES_SELECT_ELEMENT,
   EMPLOYEES_UNSELECT_ELEMENT,
   EMPLOYEES_RESET_SELECTED,
   EMPLOYEES_TOGGLE_SELECT_ALL,
   EMPLOYEES_PAGINATION_VALUE,
   EMPLOYEES_CURRENT_PAGE
}