const FETCH_USER_RESERVATIONS = 'FETCH_USER_RESERVATIONS';
const SORT_BY = 'SORT_BY';
const SORT_ORDER = 'SORT_ORDER';
const SELECT_ELEMENT = 'SELECT_ELEMENT';
const UNSELECT_ELEMENT = 'UNSELECT_ELEMENT';
const TOGGLE_SELECT_ALL = 'TOGGLE_SELECT_ALL';

export default {
   FETCH_USER_RESERVATIONS,
   SORT_BY,
   SORT_ORDER,
   SELECT_ELEMENT,
   UNSELECT_ELEMENT,
   TOGGLE_SELECT_ALL
}