const FETCH_USER_RESERVATIONS = 'FETCH_USER_RESERVATIONS';
const SEARCH_USER_RESERVATIONS = 'SEARCH_USER_RESERVATIONS';
const FILTER = 'FILTER';
const SORT_BY = 'SORT_BY';
const SORT_ORDER = 'SORT_ORDER';
const SELECT_ELEMENT = 'SELECT_ELEMENT';
const UNSELECT_ELEMENT = 'UNSELECT_ELEMENT';
const RESET_SELECTED = 'RESET_SELECTED';
const TOGGLE_SELECT_ALL = 'TOGGLE_SELECT_ALL';
const PAGINATION_VALUE = 'PAGINATION_VALUE';
const DELETE_SEARCHING_ELEMENTS = 'DELETE_SEARCHING_ELEMENTS';

export default {
   FETCH_USER_RESERVATIONS,
   SEARCH_USER_RESERVATIONS,
   FILTER,
   SORT_BY,
   SORT_ORDER,
   SELECT_ELEMENT,
   UNSELECT_ELEMENT,
   RESET_SELECTED,
   TOGGLE_SELECT_ALL,
   PAGINATION_VALUE,
   DELETE_SEARCHING_ELEMENTS
}